In [98]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [99]:
df = pd.read_csv('jd dataset.csv')

In [100]:
df.head()

,job_id,job_title,company,location,job_description,experience,education,salary_lpa,job_type,required_skills
0,JOB103863,Business Analyst,Deloitte,"Chennai, Tamil Nadu",We are hiring a Business Analyst at Deloitte i...,1-3 years,Be Computer Engineering,5.5,Contract,"SQL, JIRA, Power BI, Statistics"
1,JOB154438,Business Analyst,Persistent Systems,NaN,We are hiring a Business Analyst at Persistent...,5-8 years,MCA,8.5,Internship,"Tableau, Power BI, Excel, Statistics, SQL"
2,JOB259541,Machine Learning Engineer,Deloitte,"Nagpur, Maharashtra",We are hiring a Machine Learning Engineer at D...,8-12 years,MBA,13.0,Part-time,"Python, Scikit-learn, TensorFlow, Machine Lear..."
3,JOB134355,Python Developer,Wipro,"Remote, India",We are hiring a Python Developer at Wipro in R...,1-3 years,MSc Data Science,5.7,Full-time,"Python, REST API, Git, Docker, FastAPI, Django"
4,JOB154998,Software Engineer,Capgemini,"Bengaluru, Karnataka",We are hiring a Software Engineer at Capgemini...,2-5 years,NaN,5.0 LPA,Contract,C++ | Docker | REST API | SQL | Agile | Java

In [101]:
df.tail()

,job_id,job_title,company,location,job_description,experience,education,salary_lpa,job_type,required_skills
16845,JOB205549,DevOps Engineer,IBM,"Hyderabad, Telangana",We are hiring a DevOps Engineer at IBM in Hyde...,0-1 years,MSC DATA SCIENCE,4.7,Part-time,"Jenkins, AWS, Kubernetes, Docker, CI/CD, Git, ..."
16846,JOB140492,Data Analyst,Fractal Analytics,"Bengaluru, Karnataka",We are hiring a Data Analyst at Fractal Analyt...,1-3 years,BSc Data Science,5.9,Part-time,"NumPy, Python, SQL, Pandas, Statistics, Tablea..."
16847,JOB086107,Software Engineer,Cognida,"Noida, Uttar Pradesh",We are hiring a Software Engineer at Cognida i...,1-3 years,NaN,4.8,Internship,"Docker, REST API, Java, Git, SQL"
16848,JOB266722,Data Analyst,Deloitte,"Nashik, Maharashtra",We are hiring a Data Analyst at Deloitte in Na...,8-12 years,BCA,13.4,Internship,"Excel, Pandas, Python, Power BI, Statistics"
16849,JOB148566,Python Developer,Walmart Global Tech,"Bengaluru, Karnataka",We are hiring a Python Developer at Walmart Gl...,0-1 years,Any Graduate,4.8,Contract,"Docker, Django, REST API, Git, Python, Flask"

In [102]:
df.sample(8)

,job_id,job_title,company,location,job_description,experience,education,salary_lpa,job_type,required_skills
4900,JOB283118,Software Engineer,Persistent Systems,"ahmedabad, gujarat",We are hiring a Software Engineer at Persisten...,3-6 years,BTech Computer Science,7.9,Contract,"Python, C++, Agile, SQL, Git, REST API"
5929,JOB068725,Java Developer,Fractal Analytics,"Delhi, India",We are hiring a Java Developer at Fractal Anal...,5-8 years,BE Computer Engineering,10.0,Full-time,"Git, Spring Boot, Microservices, Hibernate, Do..."
4273,JOB081369,Web Developer,Capgemini,"Chennai, Tamil Nadu",We are hiring a Web Developer at Capgemini in ...,5-8 years,Mca,10.1,Internship,"CSS, Node.js, MongoDB, REST API"
15399,JOB122210,AI Engineer,Mphasis,"Remote, India",We are hiring a AI Engineer at Mphasis in Remo...,1-3 years,BSc Data Science,5.1,Internship,"TensorFlow, Docker, PyTorch, Machine Learning,..."
15678,JOB292925,MACHINE LEARNING ENGINEER,Cognida,"Gurugram, Haryana",We are hiring a Machine Learning Engineer at C...,3-6 years,BTECH COMPUTER SCIENCE,6.5,Contract,"Machine Learning, Docker, AWS, Scikit-learn"
1196,JOB146766,Data Engineer,IBM,"Remote, India",We are hiring a Data Engineer at IBM in Remote...,5-8 years,MBA,10.6,Internship,"SQL, Python, Azure, Databricks, ETL"
10884,JOB142938,Data Scientist,TechNova Solutions,"Bengaluru, Karnataka",We are hiring a Data Scientist at TechNova Sol...,1-3 years,MSc Data Science,5.1,Contract,"Statistics, Pandas, TensorFlow, Scikit-learn, ..."
9511,JOB122257,SQL Developer,Fractal Analytics,"Ahmedabad, Gujarat",We are hiring a SQL Developer at Fractal Anal...,5-8 years,MBA,9.2,Part-time,"PostgreSQL, Database Design, ETL, MySQL, Pytho..."

In [103]:
df.shape

(16850, 10)

In [104]:
df.columns

Index(['job_id', 'job_title', 'company', 'location', 'job_description',
       'experience', 'education', 'salary_lpa', 'job_type', 'required_skills'],
      dtype='object')

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16850 entries, 0 to 16849
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_id           16850 non-null  object
 1   job_title        16850 non-null  object
 2   company          16850 non-null  object
 3   location         16145 non-null  object
 4   job_description  16850 non-null  object
 5   experience       16341 non-null  object
 6   education        16222 non-null  object
 7   salary_lpa       16304 non-null  object
 8   job_type         16850 non-null  object
 9   required_skills  16432 non-null  object
dtypes: object(10)
memory usage: 1.3+ MB

In [106]:
df["salary_lpa"] = (
    df["salary_lpa"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace("LPA", "", case=False, regex=False)
    .str.strip()
)

df["salary_lpa"] = pd.to_numeric(df["salary_lpa"], errors="coerce")

In [107]:
df['salary_lpa'].dtype

dtype('float64')

In [108]:
df.sample(10)

,job_id,job_title,company,location,job_description,experience,education,salary_lpa,job_type,required_skills
8457,JOB079596,Power BI Developer,Bosch,"Noida, Uttar Pradesh",We are hiring a Power BI Developer at Bosch in...,0-1 years,MSc Data Science,3.7,Internship,"Power BI, ETL, Excel, DAX, Power Query, SQL"
3624,JOB188352,Java Developer,Bosch,"Mumbai, Maharashtra",We are hiring a Java Developer at Bosch in Mum...,8-12 years,MSc Data Science,12.8,Contract,"Microservices, Hibernate, Docker, Git"
7939,JOB292262,Data Scientist,LTIMindtree,"Pune, Maharashtra",We are hiring a Data Scientist at LTIMindtree ...,3-6 years,Any Graduate,7.3,Internship,"NumPy, TensorFlow, Machine Learning, Python, S..."
15131,JOB132615,Cloud Engineer,IBM,"Mumbai, Maharashtra",We are hiring a Cloud Engineer at IBM in Mumba...,3-6 years,BTech Computer Science,7.5,Internship,"AWS, CI/CD, Azure, Linux, Kubernetes, Docker"
6491,JOB025612,Java Developer,Zoho,"Delhi, India",We are hiring a Java Developer at Zoho in Delh...,1-3 years,BSc Computer Science,4.8,Internship,"Spring Boot, Microservices, REST API, Git, Jav..."
6201,JOB248999,Data Scientist,Accenture,"Hyderabad, Telangana",We are hiring a Data Scientist at Accenture in...,2-5 years,MBA,5.3,Internship,"TensorFlow, Pandas, SQL, Statistics, Machine L..."
15572,JOB085596,Data Scientist,Walmart Global Tech,"Ahmedabad, Gujarat",We are hiring a Data Scientist at Walmart Glob...,1-3 years,BCA,4.7,Internship,"Python, TensorFlow, Machine Learning, NumPy, S..."
8740,JOB254419,Software Engineer,TechNova Solutions,"Nagpur, Maharashtra",We are hiring a Software Engineer at TechNova ...,5-8 years,Any Graduate,10.6,Contract,"Java, Git, Agile, REST API, SQL, Python, C++, ..."
13595,JOB030577,Machine Learning Engineer,SIEMENS,"NAGPUR, MAHARASHTRA",We are hiring a Machine Learning Engineer at S...,0-1 years,BSc Data Science,4.1,Internship,"Scikit-learn, Docker, TensorFlow, PyTorch, Mac..."
4433,JOB100330,DATA ANALYST,Cognizant,"Noida, Uttar Pradesh",We are hiring a Data Analyst at Cognizant in N...,8-12 years,BSc Computer Science,13.7,Internship,"SQL, Power BI, Excel, Pandas, Tableau, Python,..."

In [109]:
df.isnull().sum()

job_id               0
job_title            0
company              0
location           705
job_description      0
experience         509
education          628
salary_lpa         548
job_type             0
required_skills    418
dtype: int64

In [110]:
missing_per = (df.isnull().sum() / len(df)) * 100
missing_per

job_id             0.000000
job_title          0.000000
company            0.000000
location           4.183976
job_description    0.000000
experience         3.020772
education          3.727003
salary_lpa         3.252226
job_type           0.000000
required_skills    2.480712
dtype: float64

In [111]:
df.duplicated().sum()

np.int64(256)

In [112]:
df[df.duplicated()]

,job_id,job_title,company,location,job_description,experience,education,salary_lpa,job_type,required_skills
541,JOB282810,Power BI Developer,mphasis,"Gurugram, Haryana",We are hiring a Power BI Developer at Mphasis ...,3-6 years,BTech Computer Science,7.7,Full-time,"Power Query, DAX, ETL, Data Modeling, Excel, P..."
793,JOB265896,Power BI Developer,Fractal Analytics,"Chennai, Tamil Nadu",We are hiring a Power BI Developer at Fractal ...,3-6 years,MBA,6.7,Part-time,"Data Modeling, Excel, SQL, DAX, Power Query, ETL"
949,JOB060827,Data Engineer,Infosys,"Nagpur, Maharashtra",We are hiring a Data Engineer at Infosys in Na...,8-12 years,MSc Data Science,12.6,Full-time,"SQL, Airflow, ETL, Spark, Python, AWS, Azure, ..."
1238,JOB074285,Web Developer,Zoho,"Chennai, Tamil Nadu",We are hiring a Web Developer at Zoho in Chenn...,5-8 years,BCA,10.0,Internship,"Node.js, HTML, REST API, JavaScript, MongoDB, ..."
1511,JOB139250,SQL Developer,HCLTech,"Pune, Maharashtra",We are hiring a SQL Developer at HCLTech in P...,5-8 years,BSc Computer Science,10.2,Full-time,"MySQL, PostgreSQL, SQL Server, Database Design..."
...,...,...,...,...,...,...,...,...,...,...
16636,JOB012541,Java Developer,LTIMindtree,"Chennai, Tamil Nadu",We are hiring a Java Developer at LTIMindtree ...,2-5 years,BSc Data Science,5.4,Full-time,"Docker, Spring Boot, Java, SQL"
16637,JOB287985,Python Developer,LTIMindtree,"Gurugram, Haryana",We are hiring a Python Developer at LTIMindtre...,5-8 years,MSc Data Science,10.3,Internship,"REST API, SQL, Django, Git, FastAPI"
16652,JOB176147,Data Engineer,LTIMindtree,"Nashik, Maharashtra",We are hiring a Data Engineer at LTIMindtree i...,1-3 years,Any Graduate,4.3,Part-time,Databricks | Spark | SQL | Azure | AWS | Airfl...
16813,JOB215186,Java Developer,Infosys,"Nagpur, Maharashtra",We are hiring a Java Developer at Infosys in N...,8-12 years,Any Graduate,NaN,Internship,"Hibernate, Java, Spring Boot, REST API"
16841,JOB084782,NLP Engineer,Fractal Analytics,"Delhi, India",We are hiring a NLP Engineer at Fractal Analyt...,5-8 years,MCA,8.8,Full-time,"NLP, Machine Learning, NLTK, spaCy, BERT, SQL,..."

In [113]:
df = df.drop_duplicates()

In [114]:
df.duplicated().sum()

np.int64(0)

In [115]:
df.isnull().sum()

job_id               0
job_title            0
company              0
location           697
job_description      0
experience         503
education          621
salary_lpa         535
job_type             0
required_skills    412
dtype: int64

In [116]:
df['location'] = df['location'].fillna('Unknown')

In [117]:
df['education'] = df['education'].fillna('Not Specified')

In [118]:
df['salary_lpa'] = df['salary_lpa'].fillna(df['salary_lpa'].median())

In [119]:
df.isnull().sum()

job_id               0
job_title            0
company              0
location             0
job_description      0
experience         503
education            0
salary_lpa           0
job_type             0
required_skills    412
dtype: int64

In [120]:
df.shape

(16594, 10)

In [121]:
df['experience'].unique()

array(['1-3 years', '5-8 years', '8-12 years', '2-5 years', '8-12 years ',
       '3-6 years', ' 5-8 years ', '3-6 years ', '0-1 years', nan,
       '5-8 years ', ' 1-3 years ', '0-1 years ', ' 0-1 years ',
       ' 8-12 years', ' 5-8 years', '1-3 years ', ' 2-5 years ',
       ' 3-6 years ', '2-5 years ', ' 1-3 years', ' 0-1 years',
       ' 3-6 years', ' 8-12 years ', ' 2-5 years'], dtype=object)

In [122]:
df['experience'] = (
    df['experience']
    .astype(str)
    .str.replace("years", "", case=False, regex=False) 
    .str.strip())

In [123]:
df['experience'].unique()

array(['1-3', '5-8', '8-12', '2-5', '3-6', '0-1', 'nan'], dtype=object)

In [124]:
df["experience"] = df["experience"].replace("nan", np.nan)

In [125]:
df["experience_avg"] = df["experience"].apply(
    lambda x: (float(x.split("-")[0]) + float(x.split("-")[1])) / 2
    if pd.notna(x) else np.nan
)

In [126]:
avg_experience = round(df["experience_avg"].mean(),1)

print(avg_experience)

4.5

In [127]:
df["experience_avg"] = df["experience_avg"].fillna(avg_experience)

In [128]:
df.sample(10)

,job_id,job_title,company,location,job_description,experience,education,salary_lpa,job_type,required_skills,experience_avg
9434,JOB209193,Business Analyst,Mphasis,"Mumbai, Maharashtra",We are hiring a Business Analyst at Mphasis in...,5-8,Any Graduate,9.3,Full-time,"sql,power bi,tableau,business analysis,statistics",6.5
11936,JOB044678,Java Developer,Oracle,"Ahmedabad, Gujarat",We are hiring a Java Developer at Oracle in Ah...,1-3,MSc Data Science,4.4,Internship,"Java, Docker, SQL, Spring Boot, Hibernate",2.0
8790,JOB115610,Business Analyst,Capgemini,"Gurugram, Haryana",We are hiring a Business Analyst at Capgemini ...,1-3,BCA,6.1,Full-time,"JIRA, SQL, Excel, Business Analysis",2.0
10881,JOB174281,Data Scientist,Walmart Global Tech,"noida, uttar pradesh",We are hiring a Data Scientist at Walmart Glob...,1-3,BCA,4.2,Contract,"machine learning,python,sql,pandas,scikit-learn",2.0
11045,JOB092372,Machine Learning Engineer,Amazon,"chennai, tamil nadu",We are hiring a Machine Learning Engineer at A...,3-6,MSc Data Science,8.1,Full-Time,"Scikit-learn, Python, AWS, PyTorch, Docker, Ma...",4.5
6203,JOB284987,Web Developer,TCS,"Delhi, India",We are hiring a Web Developer at TCS in Delhi ...,1-3,BCA,3.7,Full-time,"REST API, Git, MongoDB, React",2.0
10561,JOB012416,Web Developer,Cognizant,"Pune, Maharashtra",We are hiring a Web Developer at Cognizant in ...,5-8,any graduate,10.6,Contract,"React, HTML, REST API, JavaScript, Git, MongoD...",6.5
13262,JOB011547,AI Engineer,Deloitte,"Bengaluru, Karnataka",We are hiring a AI Engineer at Deloitte in Ben...,8-12,BCA,13.2,Part-time,"Python, LLM, TensorFlow, Docker, Machine Learning",10.0
3367,JOB189037,Power BI Developer,Wipro,"nashik, maharashtra",We are hiring a Power BI Developer at Wipro in...,3-6,BE Computer Engineering,6.7,Full-time,"DAX, Data Modeling, Excel, Power BI, ETL, Powe...",4.5
9410,JOB052600,Cloud Engineer,Cognida,"Nagpur, Maharashtra",We are hiring a Cloud Engineer at Cognida in ...,5-8,BE Computer Engineering,9.2,Internship,"AWS, Kubernetes, Terraform, Azure, Linux, Dock...",6.5

In [129]:
df.isnull().sum()

job_id               0
job_title            0
company              0
location             0
job_description      0
experience         503
education            0
salary_lpa           0
job_type             0
required_skills    412
experience_avg       0
dtype: int64

In [130]:
df[df["experience"].isna()]

,job_id,job_title,company,location,job_description,experience,education,salary_lpa,job_type,required_skills,experience_avg
37,JOB007629,Sql Developer,Amazon,"Nashik, Maharashtra",We are hiring a SQL Developer at Amazon in Nas...,NaN,BSc Computer Science,13.5,Internship,"SQL Server, Python, SQL, Database Design, ETL,...",4.5
65,JOB076910,Web Developer,Wipro,"Hyderabad, Telangana",We are hiring a Web Developer at Wipro in Hyde...,NaN,BTech Computer Science,10.4,Contract,"Git, REST API, React, HTML, JavaScript, CSS, M...",4.5
154,JOB281207,Software Engineer,TCS,"Nagpur, Maharashtra",We are hiring a Software Engineer at TCS in Na...,NaN,MBA,6.2,Contract,"Docker, REST API, SQL, Git, C++",4.5
167,JOB093014,Data Engineer,IBM,"Ahmedabad, Gujarat",We are hiring a Data Engineer at IBM in Ahmed...,NaN,BTech Computer Science,5.1,Contract,"SQL, AWS, Azure, Databricks, Airflow, ETL, Spa...",4.5
169,JOB278081,Business Analyst,HCLTech,Unknown,We are hiring a Business Analyst at HCLTech in...,NaN,BSc Data Science,12.5,Part-time,"Business Analysis, JIRA, SQL, Statistics",4.5
...,...,...,...,...,...,...,...,...,...,...,...
16649,JOB051709,Machine Learning Engineer,IBM,"Pune, Maharashtra",We are hiring a Machine Learning Engineer at I...,NaN,MSc Data Science,6.7,Contract,"Machine Learning, SQL, Python, TensorFlow, Docker",4.5
16665,JOB130881,Software Engineer,Microsoft,"Remote, India",We are hiring a Software Engineer at Microsoft...,NaN,bsc data science,3.2,Part-time,"C++, SQL, Git, Docker, REST API",4.5
16773,JOB000001,DevOps Engineer,Wipro,"PUNE, MAHARASHTRA",We are hiring a DevOps Engineer at Wipro in P...,NaN,BE Computer Engineering,11.8,Part-time,"Kubernetes, AWS, Linux, Git, Terraform",4.5
16816,JOB072240,Power BI Developer,Amazon,"delhi, india",We are hiring a Power BI Developer at Amazon i...,NaN,MSc Data Science,8.1,Part-time,"Data Modeling, DAX, Power Query, ETL",4.5
16840,JOB219711,Data Analyst,TECH MAHINDRA,"Hyderabad, Telangana",We are hiring a Data Analyst at Tech Mahindra ...,NaN,Be Computer Engineering,8.2,Full-time,"Power BI, Tableau, Pandas, SQL, NumPy, Python",4.5

In [131]:
df = df.dropna(subset=['required_skills']).reset_index(drop=True)

In [142]:
df['experience'] = df['experience'].fillna(round(df['experience_avg'].mean(),1))

In [141]:
df.iloc[[37,65]]

,job_id,job_title,company,location,job_description,experience,education,salary_lpa,job_type,required_skills,experience_avg
37,JOB007629,Sql Developer,Amazon,"Nashik, Maharashtra",We are hiring a SQL Developer at Amazon in Nas...,4.547522,BSc Computer Science,13.5,Internship,"SQL Server, Python, SQL, Database Design, ETL,...",4.5
65,JOB024784,Power BI Developer,HCLTech,"Noida, Uttar Pradesh",We are hiring a Power BI Developer at HCLTech ...,2-5,MBA,6.7,Part-time,"Data Modeling, Excel, SQL, ETL",3.5

(16182, 11)

In [143]:
df.isnull().sum()

job_id             0
job_title          0
company            0
location           0
job_description    0
experience         0
education          0
salary_lpa         0
job_type           0
required_skills    0
experience_avg     0
dtype: int64

In [144]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16182 entries, 0 to 16181
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_id           16182 non-null  object
 1   job_title        16182 non-null  object
 2   company          16182 non-null  object
 3   location         16182 non-null  object
 4   job_description  16182 non-null  object
 5   experience       16182 non-null  object
 6   education        16182 non-null  object
 7   salary_lpa       16182 non-null  float64
 8   job_type         16182 non-null  object
 9   required_skills  16182 non-null  object
 10  experience_avg   16182 non-null  float64
dtypes: float64(2), object(9)
memory usage: 1.4+ MB